//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lavomaticApp.Dal
{
    using System;

    public partial class Washer
    {
        public long IdLaundry { get; set; }
        public Nullable<int> Weight { get; set; }
        public Nullable<int> Number { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> PriceWithDisinfectant { get; set; }
    
        public virtual Laundry Laundry { get; set; }
    }
}
